name: 'Setup Go'
description: 'Setup Go and its dependencies'
inputs:
  go-version:  # id of input
    description: 'go version'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495 # v3.6.1
      with:
        go-version: ${{ inputs.go-version }}
    - uses: actions/cache@2b250bc32ad02700b996b496c14ac8c2840a2991 # v2.1.8
      with:
        path: |
          ~/go/pkg/mod
          vendor
        key: ${{ runner.os }}-go-${{ inputs.go-version }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ inputs.go-version }}-
    - name: Setup deps
      shell: bash
      run: |
        go mod download
        go mod tidy
        go mod vendor
